### ISSUE TITLE
x86_64 does not compile on Clang 4.0

### ISSUE THREAD

**Issue by navidR** [hioa-cs/IncludeOS#1412]
`/home/navid/development/IncludeOS/src/kernel/irq_manager.cpp:136:8: error: %rip can only be used as a base register
asm ("movq %%rip, %0" : "=d" (regs[16]));`

**Comment by fwsGonzo** [comment]
It's already fixed on dev: https://github.com/hioa-cs/IncludeOS/issues/1388

**Comment by navidR** [comment]
It's okay to close this. I haven't merged the dev and when I searched for this bug I wasn't careful enough ;)
