### ISSUE TITLE
/examples/tcp does not build in 0.8

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#579]
When I try to build /examples/tcp using the supplied makefile, it fails to compile. 

Error messages (abbreviated);

service.cpp:42:18: error: no matching constructor for initialization of 'net::TCP::Socket'
net::TCP::Socket python_server{ {{10,0,2,2}} , 1337};

service.cpp:65:25: error: no matching constructor for initialization of 'IP4::addr'
  inet->network_config( {{ 10,0,0,42 }},      // IP

service.cpp:72:31: note: candidate function [with $0 = bool] not viable: expects an l-value for 1st argument

**Comment by fwsGonzo** [comment]
you mean the tcp example?

**Comment by ingve** [comment]
Yes, sorry, examples/tcp. PBCAK error while copying from the gitter chat.

**Comment by alfred-bratterud** [comment]
I fixed the IP interface locally but it's still an issue with `inet->dhclient()->on_config([&server](auto&)`.

**Comment by alfred-bratterud** [comment]
This is now fixed in #573 for dev. Since it also affects master I'll leave this open and try to cherry-pick the patch there.
