### PR TITLE
Point dev solo5 to v0.3.0

### PR DESCRIPTION
**Pull request by ricarkol**
This is mainly for #1515 as solo5 version (0.3.0) has a fix for it. The solo5 interface changed slightly for 0.3.0 like function names, and args to `solo5_app_main` and the block ones (offsets are now bytes and not sectors anymore). All changes were straightforward except `src/drivers/solo5blk.cpp`: might not be doing the right thing with the smart pointers used for buffers (specially how to release them on error).

Tested with `tetst/misc/ukvm/test.sh` and `test/fs/integration/fat32` on an `Ubuntu 16.04` using clang 6.0.

### CODE REVIEW

**Comment by mywtfmp3** [comment]
Fail to compile on gcc 8.1.1 on Arch Linux. 
```bash
[  0%] No patch step for 'solo5_repo'
[  0%] No update step for 'solo5_repo'
[ 33%] Performing configure step for 'solo5_repo'
[ 33%] Performing build step for 'solo5_repo'
mem.c: In function ‘mem_init’:
mem.c:57:5: error: array subscript -1 is below array bounds of ‘char[]’ [-Werror=array-bounds]
     log(INFO, "Solo5:     unused @ (0x0 - 0x%lx)\n", &_stext[-1]);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mem.c:58:5: error: array subscript -1 is below array bounds of ‘char[]’ [-Werror=array-bounds]
     log(INFO, "Solo5:       text @ (0x%lx - 0x%lx)\n", &_stext, &_etext[-1]);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mem.c:59:5: error: array subscript -1 is below array bounds of ‘char[]’ [-Werror=array-bounds]
     log(INFO, "Solo5:     rodata @ (0x%lx - 0x%lx)\n", &_etext, &_erodata[-1]);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mem.c:60:5: error: array subscript -1 is below array bounds of ‘char[]’ [-Werror=array-bounds]
     log(INFO, "Solo5:       data @ (0x%lx - 0x%lx)\n", &_erodata, &_end[-1]);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [GNUmakefile:98: mem.o] Error 1
make[4]: *** [GNUmakefile:39: ukvm] Error 2
make[3]: *** [CMakeFiles/solo5_repo.dir/build.make:112: precompiled/src/solo5_repo-stamp/solo5_repo-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:216: CMakeFiles/solo5_repo.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:191: CMakeFiles/PrecompiledLibraries.dir/rule] Error 2
make: *** [Makefile:225: PrecompiledLibraries] Error 2
>>> Sorry <<<
Could not install from bundle.
```

Set gcc version to `gcc-7` in file `cmake/cross_compiled_libraries.cmake` fixes the problem. The `solo5` repo master branch no longer use negative array index. See https://github.com/Solo5/solo5/blob/master/kernel/mem.c#L53
```bash
if (WITH_SOLO5)
ExternalProject_Add(solo5_repo
        PREFIX precompiled
        BUILD_IN_SOURCE 1
        GIT_REPOSITORY https://github.com/solo5/solo5.git
        GIT_TAG v0.3.0
        CONFIGURE_COMMAND CC=gcc-7 ./configure.sh
        UPDATE_COMMAND ""
        BUILD_COMMAND make
        INSTALL_COMMAND ""
)
```

**Comment by ricarkol** [comment]
Fix is more recent than version 0.3.0 (didn't notice that). Preparing another PR.
