### ISSUE TITLE
includeos doesn't compile on Ubuntu 17.10

### ISSUE THREAD

**Issue by perbu** [hioa-cs/IncludeOS#1648]
IncludeOS doesn't compile on Ubuntu 17.10. On a system without clang 3.8 it spits out this:

>>> Installing missing dependencies (requires sudo):
[sudo] password for ubuntu:
E: The repository 'http://apt.llvm.org/artful llvm-toolchain-artful-3.8 Release' does not have a Release file.
>>> Sorry <<<
Could not install dependencies

If I install clang 3.8 we  get a bit further:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/cstdlib:77:
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:102:3: error:
      support for type '__float128' is not yet implemented
  abs(__float128 __x)
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:102:18: error:
      support for type '__float128' is not yet implemented
  abs(__float128 __x)

So Clang 3.8 can't compile the GCC 7 libs. I tried overriding install.sh and etc/install_dependencies_linux.sh and build again but there are still some artifacts left from the previous build attempt. Don't know how to fix this.  However, in a clean tree and getting some help from @alfred-bratterud we ended up with the following changes:

ubuntu@vaskemaskin:~/IncludeOS$ git diff
diff --git a/etc/install_dependencies_linux.sh b/etc/install_dependencies_linux.sh
index a31f3dcf..cb6635cf 100755
--- a/etc/install_dependencies_linux.sh
+++ b/etc/install_dependencies_linux.sh
@@ -7,7 +7,8 @@
 ############################################################

 BUILD_DEPENDENCIES="curl make cmake nasm bridge-utils qemu jq python-pip g++-multilib gcc"
-[ ! -z "$CC" ] && { CLANG_VERSION=${CC: -3}; } || CLANG_VERSION="3.8"
+#[ ! -z "$CC" ] && { CLANG_VERSION=${CC:-4}; } || CLANG_VERSION="4.0"
+CLANG_VERSION=4.0
 TEST_DEPENDENCIES="g++"
 PYTHON_DEPENDENCIES="jsonschema psutil junit-xml filemagic"
 INSTALLED_PIP=0
diff --git a/install.sh b/install.sh
index d8369991..38bef318 100755
--- a/install.sh
+++ b/install.sh
@@ -247,8 +247,8 @@ fi

 printf "\n\n>>> IncludeOS installation Done!\n"
 printf "    %s\n" "To use IncludeOS set env variables for cmake to know your compiler, e.g.:"\
-          '    export CC="clang-3.8"'\
-          '    export CXX="clang++-3.8"'\
+          '    export CC="clang-$clang_version"'\
+          '    export CXX="clang++-$clang_version"'\
           ""\
           "Test your installation with ./test.sh"

Now it builds, installs and runs nicely. We should require clang 4.0 to build from now on, methinks. Long term goal should be removing the dependency on GCC libs, but that might be tricky.

**Comment by karra88** [comment]
I have faced the same error "support for type '__float128' is not yet implemented" with clang3.8 and changed to clang3.9 on Ubuntu14.04. 

Now I am not facing the above error but when I tried to install, I am getting the error mentioned in #1385 

![includeos](https://user-images.githubusercontent.com/12840300/35547055-e42b265c-059c-11e8-9a85-b6a4023ab900.png)

**Comment by jeannekamikaze** [comment]
I seem to be getting the same '__float128' support error even after applying the patch above on a clean tree. Was there any other change you made to get the thing to build?

**Comment by fwsGonzo** [comment]
Try installing clang-5.0 and set CC to clang-5.0 and CXX to clang++-5.0 then install.sh again

**Comment by jeannekamikaze** [comment]
That worked, thanks!
